### PR TITLE
Version 1.5 of C# and Python code

### PR DESCRIPTION
**Pull request by RusMermaid**
You can change Python code back into v2.0.5 in 'HilbertsCurve_Python' folder, but I have translated this project to C#

### CODE REVIEW

**Comment by galtay** [comment]
Hi @RusMermaid , this looks like a cool project, but I don't think this repo is the right place for it. I would encourage you to start a new repo and just mention that your C# implementation is based on this one

**Comment by RusMermaid** [comment]
> Hi @RusMermaid , this looks like a cool project, but I don't think this repo is the right place for it. I would encourage you to start a new repo and just mention that your C# implementation is based on this one

https://github.com/RusMermaid/Hilberts_Curve_CS Is the project

**Comment by RusMermaid** [comment]
> Hi @RusMermaid , this looks like a cool project, but I don't think this repo is the right place for it. I would encourage you to start a new repo and just mention that your C# implementation is based on this one

I’d prefer to merge our projects

**Comment by galtay** [comment]
sorry, but I'd prefer they remain separate.

**Pull request closed without merging**
